########  /usr/share/kibana/config
server.name: kibana
server.host: "0"
status.allowAnonymous: true
elasticsearch.hosts: [ "http://192.168.0.197:9200" ]
#elasticsearch.username:
#elasticsearch.password:
xpack.monitoring.ui.container.elasticsearch.enabled: true