headPlugin:
  image: docker.elastic.co/kibana/kibana:7.5.0
  container_name: kibana
  restart: always
  ports:
       - 5601:5601
  networks: elastic-networks
  environment:
       TZ : "Asia/Shanghai"