elasticsearch:
  container_name: elasticsearch
  image: registry.cn-hangzhou.aliyuncs.com/lcts/elasticsearch-server:latest
  ports:
       - 9200:9200
       - 9300:9300
  environment:
       TZ : "Asia/Shanghai"
       cluster.name: sn-cluster
